# Generated by Django 5.2.15 on 2026-07-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='country_name',
            field=models.CharField(default='IN', max_length=50),
        ),
    ]
