# Generated by Django 5.2.15 on 2026-07-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_brand_country_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studenttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
    ]
