# Generated by Django 5.2.15 on 2026-07-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttable',
            name='age',
        ),
        migrations.RemoveField(
            model_name='studenttable',
            name='dob',
        ),
        migrations.AddField(
            model_name='studenttable',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='studenttable',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
